---
title: "scratch"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```



```{r}
data(aus_production)
aus_production %>% gg_season(Beer)
aus_production %>% gg_subseries(Beer)
aus_production %>% filter(year(Quarter) > 1991) %>% gg_lag(Beer)
aus_production %>% ACF(Beer) %>% autoplot()

dcmp <- aus_production %>%
  model(STL(Beer ~ season(window = Inf)))
components(dcmp)

components(dcmp) %>% autoplot()
```




```{r}

data(tourism)

tourism %>% 
  features(Trips, features = feature_set(tags = "autocorrelation"))

```





@misc{rozemberczki2021pytorch, 
author = {Benedek Rozemberczki and Paul Scherer and Yixuan He and George Panagopoulos and Maria Astefanoaei and Oliver Kiss and Ferenc Beres and Nicolas Collignon and Rik Sarkar}, 
title = {{PyTorch Geometric Temporal: Spatiotemporal Signal Processing with Neural Machine Learning Models}}, 
year = {2021}, 
eprint = {[Web Link]}, 
}

```{r pedalme}
destfile <- tempfile()
download.file("https://archive.ics.uci.edu/ml/machine-learning-databases/00613/pedalme_.zip",destfile)
df <-  read.csv(unz(destfile, "pedalme_features.csv"), header = FALSE)
names(df) <- c('X','year','week','location','time','demand')
unlink(destfile)


```





```{r wine}
destfile <- tempfile()
download.file("https://archive.ics.uci.edu/ml/machine-learning-databases/wine/wine.data", destfile)
df <- read.csv(destfile, header = FALSE)
names(df) <- c('Class','Alcohol','Malic acid','Ash','Alcalinity of ash','Magnesium', 
'Total phenols','Flavanoids','Nonflavanoid phenols','Proanthocyanins' 
,'Color intensity','Hue','OD280/OD315 of diluted wines','Proline')


```



```{r amazon}

library(archive)
library(readr)
library(dplyr)

destfile <- tempfile()
download.file("https://archive.ics.uci.edu/ml/machine-learning-databases/00216/amzn-anon-access-samples.tgz", destfile)
df <- read_csv(archive_read(destfile, file = 'amzn-anon-access-samples-history-2.0.csv'))
df$REQUEST_DATE <- as.Date(df$REQUEST_DATE)
df$AUTHORIZATION_DATE <- as.Date(df$AUTHORIZATION_DATE)
df <- df %>% rename(
    ds = REQUEST_DATE,
    y = LOGIN
)

```



```{r air}
library(tidyr)
library(lubridate)


destfile <- tempfile()
download.file("https://archive.ics.uci.edu/ml/machine-learning-databases/00360/AirQualityUCI.zip",destfile)
df <-  read.csv(unz(destfile, "AirQualityUCI.csv"), sep = ";" ,header = TRUE)
df$ds <- as_datetime(as.POSIXct(paste(df$Date, df$Time), format = "%m/%d/%Y%H.%M.%S"))
df$y <- as.numeric(df$CO.GT.)
df <- df %>% drop_na(c(ds,y))


```


```{r traffic}

library(archive)
library(readr)
library(dplyr)


destfile <- tempfile()
download.file("https://archive.ics.uci.edu/ml/machine-learning-databases/00492/Metro_Interstate_Traffic_Volume.csv.gz",destfile)
df <- read_csv(destfile)
df$ds <- df$date_time
df$y <- df$traffic_volume
df <- df %>% drop_na(c(ds,y))

```





```{r}
destfile <- tempfile()
download.file("https://archive.ics.uci.edu/ml/machine-learning-databases/00360/AirQualityUCI.zip",destfile)
df <-  read.csv(unz(destfile, "AirQualityUCI.csv"), sep = ";" ,header = TRUE)
df$ds <- as.POSIXlt(paste(df$Date, df$Time), format = "%d/%m/%Y%H.%M.%S")
df$y <- as.numeric(df$CO.GT.)
df <- df |> tidyr::drop_na(c(ds,y))


m <- prophet(df)
future <- make_future_dataframe(m, periods = 30, freq = 'week')
tail(future)

forecast <- predict(m, future)
tail(forecast[c('ds', 'yhat', 'yhat_lower', 'yhat_upper')])
plot(m, forecast)
prophet_plot_components(m, forecast)

dyplot.prophet(m, forecast)

```




```{r}

library(prophet)
library(dplyr)

destfile <- tempfile()
download.file("https://archive.ics.uci.edu/ml/machine-learning-databases/00360/AirQualityUCI.zip",destfile)
df <-  read.csv(unz(destfile, "AirQualityUCI.csv"), sep = ";" ,header = TRUE)
#df$ds <- as.POSIXlt(paste(df$Date, df$Time), format = "%m/%d/%Y%H.%M.%S")
df$ds <- as.POSIXlt(paste(df$Date, df$Time), format = "%d/%m/%Y%H.%M.%S")
df$y <- as.numeric(df$CO.GT.)
df <- df |> tidyr::drop_na(c(ds,y))
df <- df %>% filter(!is.na(ds))


m <- prophet(df, yearly.seasonality=FALSE)
future <- make_future_dataframe(m, periods = 30, freq = 'week')
forecast <- predict(m, future)
plot(m, forecast)
prophet_plot_components(m, forecast)


```



```{r timeseries}


#library(dplyr)
# library(tidyr)
# library(forecast)
# library(lubridate)
# library(archive)
# library(readr)
#library(yardstick)


# These assume working from development directory structure
#ml_datasets <- mldash::read_ml_datasets(dir = 'inst/datasets',cache_dir = 'inst/datasets')
ml_datasets <- mldash::read_ml_datasets(dir = 'inst/datasets')
ml_models <- mldash::read_ml_models(dir = 'inst/models')


# Run only classification models/datasets
ml_datasets <- ml_datasets |> dplyr::filter(ml_datasets$type == 'timeseries')
ml_models <- ml_models |> dplyr::filter(ml_models$type == 'timeseries')

ml_results2 <- mldash::run_models(datasets = ml_datasets,
								 models = ml_models,
								 print_errors = TRUE,
								 seed = 1234)

```



```{r}
#devtools::install_github("FinYang/tsdl")

library(tsdl)
library(forecast)
tsdl

a <- subset(tsdl,"Sales")
b <- a %>% as_tsibble(index = ds)

```
















```{r}

visitors <- tourism %>%
  group_by(State) %>%
  summarise(Trips = sum(Trips))
visitors %>%
  ggplot(aes(x = Quarter, y = Trips)) +
  geom_line() +
  facet_grid(vars(State), scales = "free_y") +
  labs(title = "Australian domestic tourism",
       y= "Overnight trips ('000)")


t0 <- visitors %>%
  pivot_wider(values_from=Trips, names_from=State) %>%
  GGally::ggpairs(columns = 2:9)


```






```{r}

data(us_employment)

us_retail_employment <- us_employment %>%
  filter(year(Month) >= 1990, Title == "Retail Trade") %>%
  select(-Series_ID)
autoplot(us_retail_employment, Employed) +
  labs(y = "Persons (thousands)",
       title = "Total employment in US retail")


dcmp <- us_retail_employment %>%
  model(stl = STL(Employed))
components(dcmp)

components(dcmp) %>%
  as_tsibble() %>%
  autoplot(Employed, colour="gray") +
  geom_line(aes(y=trend), colour = "#D55E00") +
  labs(
    y = "Persons (thousands)",
    title = "Total employment in US retail"
  )

components(dcmp) %>% autoplot()

```





```{r}


library(fpp3)



dcmp <- us_retail_employment %>%
  model(stl = STL(Employed))
components(dcmp)


components(dcmp) %>%
  as_tsibble() %>%
  autoplot(Employed, colour="gray") +
  geom_line(aes(y=trend), colour = "#D55E00") +
  labs(
    y = "Persons (thousands)",
    title = "Total employment in US retail"
  )


components(dcmp) %>% autoplot()


```








```{r prophet covid data}

df <- read.csv("https://raw.githubusercontent.com/nytimes/covid-19-data/master/us.csv")
df <- df %>% fill(cases, .direction = 'up')
df$ds <- as_datetime(as.POSIXct(df$date, format = "%Y-%m-%d"))
df$y <- df$cases

m <- prophet(df,seasonality.mode = 'multiplicative', changepoint.prior.scale = 0.001)

future <- make_future_dataframe(m, periods = 208, freq = 'day')
tail(future)

forecast <- predict(m, future)
tail(forecast[c('ds', 'yhat', 'yhat_lower', 'yhat_upper')])

plot(m, forecast) + add_changepoints_to_plot(m)
prophet_plot_components(m, forecast)
dyplot.prophet(m, forecast)

```






```{r prophet sample usage}

df <- read.csv('https://raw.githubusercontent.com/facebook/prophet/main/examples/example_wp_log_peyton_manning.csv')

m <- prophet(df, seasonality.mode = 'multiplicative', changepoint.prior.scale = 0.01)

future <- make_future_dataframe(m, periods = 208, freq = 'week')
tail(future)

forecast <- predict(m, future)
tail(forecast[c('ds', 'yhat', 'yhat_lower', 'yhat_upper')])

plot(m, forecast) + add_changepoints_to_plot(m)
prophet_plot_components(m, forecast)
dyplot.prophet(m, forecast)

```






```{r}

google_2015 <- gafa_stock %>%
  filter(Symbol == "GOOG", year(Date) == 2015) 


google_2015 %>% ACF(Close) %>% 
  autoplot() + labs(subtitle = "Google closing stock price")

google_2015 %>% ACF(difference(Close)) %>% 
  autoplot() + labs(subtitle = "Changes in Google closing stock price")

```


```{r}
google_2015 %>%
  mutate(diff_close = difference(Close)) %>%
  features(diff_close, ljung_box, lag = 10)


```



# Stationarity Testing



```{r}

t = 0:300
y_stationary <- rnorm(length(t),mean=1,sd=1) # the stationary time series (ts)
y_trend      <- cumsum(rnorm(length(t),mean=1,sd=4))+t/100 # our ts with a trend
# lets normalize each for simplicity
y_stationary<- y_stationary/max(y_stationary) 
y_trend      <- y_trend/max(y_trend) 

```




```{r}

plot.new()
#frame()
#par(mfcol=c(2,2))
# the stationary signal and ACF
plot(t,y_stationary,
     type='l',col='red',
     xlab = "time (t)",
     ylab = "Y(t)",
     main = "Stationary signal")
acf(y_stationary,lag.max = length(y_stationary),
         xlab = "lag #", ylab = 'ACF',main=' ')
# the trend signal and ACF
plot(t,y_trend,
     type='l',col='red',
     xlab = "time (t)",
     ylab = "Y(t)",
     main = "Trend signal")
acf(y_trend,lag.max = length(y_trend),
         xlab = "lag #", ylab = 'ACF', main=' ')

```



```{r}

lag.length = 25
Box.test(y_stationary, lag=lag.length, type="Ljung-Box") # test stationary signal

Box.test(y_trend,      lag=lag.length, type="Ljung-Box") # test nonstationary signal




```



```{r}
library(tseries)

kpss.test(y_stationary, null="Trend")
kpss.test(y_trend, null="Trend")

```






```{r}
global_economy %>%
  filter(Code == "CAF") %>%
  autoplot(Exports) +
  labs(title="Central African Republic exports",
       y="% of GDP")
```



```{r}

g_df <- global_economy %>% drop_na()

# Ljung-Box test for independence (a non-stationary signal will have a low p-value)
lag.length = 18
Box.test(g_df$Exports, lag=lag.length, type="Ljung-Box")

# Augmented Dickey–Fuller (ADF) t-statistic test for unit root (a series with a trend line will have a unit root and result in a large p-value)
adf.test(g_df$Exports)

acf(g_df$Exports,lag.max = length(g_df$Exports),
         xlab = "lag #", ylab = 'ACF',main=' ')

# Kwiatkowski-Phillips-Schmidt-Shin (KPSS) for level or trend stationarity (a low p-value will indicate a signal that is not trend stationary, has a unit root)
kpss.test(g_df$Exports, null="Trend")


```



```{r}

global_economy %>%
  filter(Code == "CAF") %>%
  gg_tsdisplay(difference(Exports), plot_type='partial')

```







```{r}

g_df$y <- difference(g_df$Exports)

g_df <- g_df %>% drop_na()

# Ljung-Box test for independence (a non-stationary signal will have a low p-value)
lag.length = 18
Box.test(g_df$y, lag=lag.length, type="Ljung-Box")

# Augmented Dickey–Fuller (ADF) t-statistic test for unit root (a series with a trend line will have a unit root and result in a large p-value)
adf.test(g_df$y)

acf(g_df$y,lag.max = length(g_df$y),
         xlab = "lag #", ylab = 'ACF',main=' ')

# Kwiatkowski-Phillips-Schmidt-Shin (KPSS) for level or trend stationarity (a low p-value will indicate a signal that is not trend stationary, has a unit root)
kpss.test(g_df$y, null="Trend")


```


```{r}

caf_fit <- global_economy %>%
  filter(Code == "CAF") %>%
  model(arima210 = ARIMA(Exports ~ pdq(2,1,0)),
        arima013 = ARIMA(Exports ~ pdq(0,1,3)),
        stepwise = ARIMA(Exports),
        search = ARIMA(Exports, stepwise=FALSE))

caf_fit %>% pivot_longer(!Country, names_to = "Model name", values_to = "Orders")

glance(caf_fit) %>% arrange(AICc) %>% select(.model:BIC)
caf_fit %>% tidy()
accuracy(caf_fit)

```



```{r}

caf_fit %>%
  select(search) %>%
  gg_tsresiduals()

```

```{r}

augment(caf_fit) %>%
  filter(.model=='search') %>%
  features(.innov, ljung_box, lag = 10, dof = 3)

```


```{r}

caf_fit %>%
  forecast(h=50) %>%
  filter(.model=='search') %>%
  autoplot(global_economy)

```








```{r}
df <- read.csv('https://raw.githubusercontent.com/ourcodingclub/CC-time-series/master/monthly_milk.csv')
df$month = as.Date(df$month)
head(df)


df.ts = ts(df[, -1], frequency = 12, start=c(1962, 1, 1))
head(df.ts)

plot(df.ts)

# Using the ADF Test
adf.test(df.ts)

#  Ljung-Box test
Box.test(df.ts, lag=12, type="Ljung-Box") 





```



```{r}

tb <- df %>% as_tsibble(index = month)
tb %>% autoplot(milk_prod_per_cow_kg)


tb$y <- difference(tb$milk_prod_per_cow_kg)
tb <- tb %>% drop_na()
tb %>% autoplot(y)

```

```{r}

# Ljung-Box test for independence (a non-stationary signal will have a low p-value)
lag.length = 15
Box.test(tb$milk_prod_per_cow_kg, lag=lag.length, type="Ljung-Box")

# Augmented Dickey–Fuller (ADF) t-statistic test for unit root (a series with a trend line will have a unit root and result in a large p-value)
adf.test(tb$milk_prod_per_cow_kg)

acf(tb$milk_prod_per_cow_kg,lag.max = length(tb$milk_prod_per_cow_kg),
         xlab = "lag #", ylab = 'ACF',main=' ')

# Kwiatkowski-Phillips-Schmidt-Shin (KPSS) for level or trend stationarity (a low p-value will indicate a signal that is not trend stationary, has a unit root)
kpss.test(tb$milk_prod_per_cow_kg, null="Trend")


# Ljung-Box test for independence (a non-stationary signal will have a low p-value)
lag.length = 15
Box.test(tb$y, lag=lag.length, type="Ljung-Box")

# Augmented Dickey–Fuller (ADF) t-statistic test for unit root (a series with a trend line will have a unit root and result in a large p-value)
adf.test(tb$y)

acf(tb$y,lag.max = length(tb$y),
         xlab = "lag #", ylab = 'ACF',main=' ')

# Kwiatkowski-Phillips-Schmidt-Shin (KPSS) for level or trend stationarity (a low p-value will indicate a signal that is not trend stationary, has a unit root)
kpss.test(tb$y, null="Trend")

```





```{r}

tb2 <- tb %>% select(month,y)

# Ljung-Box test for independence (a non-stationary signal will have a low p-value)
lag.length = 15
Box.test(tb2$y, lag=lag.length, type="Ljung-Box")

# Augmented Dickey–Fuller (ADF) t-statistic test for unit root (a series with a trend line will have a unit root and result in a large p-value)
adf.test(tb2$y)

acf(tb2$y,lag.max = length(tb2$y),
         xlab = "lag #", ylab = 'ACF',main=' ')

# Kwiatkowski-Phillips-Schmidt-Shin (KPSS) for level or trend stationarity (a low p-value will indicate a signal that is not trend stationary, has a unit root)
kpss.test(tb2$y, null="Trend")



```







```{r}

# examples from base
difference(1:10, 2)
difference(1:10, 2, 2)
x <- cumsum(cumsum(1:10))
difference(x, lag = 2)
difference(x, differences = 2)
# Use order_by if data not already ordered (example from dplyr)
library(dplyr, warn.conflicts = FALSE)
tsbl <- tsibble(year = 2000:2005, value = (0:5)^2, index = year)
scrambled <- tsbl %>% slice(sample(nrow(tsbl)))
scrambled

wrong <- mutate(scrambled, diff = difference(value))
arrange(wrong, year)

right <- mutate(scrambled, diff = difference(value, order_by = year))
arrange(right, year)

```

	
	
	
	
	
	
	
	
	
	
```{r}

	destfile <- tempfile()
	download.file("https://datahub.io/core/s-and-p-500/r/data.csv",destfile)
	df <-  readr::read_csv(destfile)
	df$ds <- df$Date
	df$ds <- tsibble::yearmonth(df$ds)
	df$y <- df$SP500
	df <- df %>% dplyr::filter(ds > as.Date("2000-01-01"))
	df <- mutate(df, y = difference(y, order_by = ds, lag = 2, default = 0))

	df <- df |> tidyr::drop_na(c(ds,y)) |> dplyr::distinct(ds,y)
	df <- df |> dplyr::filter(!is.na(ds))

	tb <- df |> dplyr::select(y, ds) |> tsibble::as_tsibble(index = ds)
	tb <- tsibble::fill_gaps(tb, .full = TRUE, y = dplyr::last(y))
	
	
	
	tb <- tb %>% dplyr::filter(ds > as.Date("2000-01-01"))
	tb <- mutate(tb, y = difference(y, order_by = ds, lag = 3, default = 0))
	
	tb %>% autoplot(y)



```
	


```{r}

# Ljung-Box test for independence (a non-stationary signal will have a low p-value)
print('=====')
bt_test <- Box.test(a_tb$y, lag=lag.length, type="Ljung-Box")
bt_test
print(paste0('- Ljung-Box test (stationary): ', bt_test$p.value > 0.05, ' at a p-value of ', round(bt_test$p.value,4)) )

# Augmented Dickey–Fuller (ADF) t-statistic test for unit root (a series with a trend line will have a unit root and result in a large p-value)
#H0 - The time series is non-stationary.
#HA - The time series is stationary.
print('')
print('=====')
adf_test <- adf.test(x=a_tb$y)
adf_test
#acf(a_tb$y,lag.max = length(a_tb$y),xlab = "lag #", ylab = 'ACF',main=' ')
print(paste0('- Dickey–Fuller (ADF) (stationary): ', adf_test$p.value < 0.05, ' at a p-value of ', round(adf_test$p.value,4)) )

# Kwiatkowski-Phillips-Schmidt-Shin (KPSS) for level or trend stationarity (a low p-value will indicate a signal that is not trend stationary, has a unit root)
print('')
print('=====')
kpss_test <- kpss.test(a_tb$y, null="Trend")
kpss_test
print(paste0('- Kwiatkowski-Phillips-Schmidt-Shin (KPSS) (trend stationary): ', kpss_test$p.value < 0.05, ' at a p-value of ', round(kpss_test$p.value,4)) )


```






```{r}

# train model
fit <- train_data %>%
  model(arima = ARIMA(y))

	tryCatch( {gg_arma(fit %>% select(arima))},
			  error=function(e) { message(e)})

fit %>% report()

#components(fit) %>% autoplot()


	tryCatch( {fit %>% gg_tsresiduals()},
		  error=function(e) { message(e)})

	
m0 <- fabletools::accuracy(fit)
m0 <- m0 %>% pivot_longer(!c('.model','.type') ,names_to = ".metric", values_to = "fable")
m0$.metric <- tolower(m0$.metric)

# test model
fc <- fit %>% fabletools::forecast(new_data = new_data)
fc %>% autoplot(train_data)

data_df <- data.frame(
	predict =fc$.mean,
	actual = valid_data$y,
	month = valid_data$ds
)
arima_plt <- ggplot(data_df, aes(x=month)) +
				geom_line(aes(y=actual), color="darkgray") +
				geom_line(aes(y=predict), color="steelblue", linetype="twodash") +
				ggtitle("Arima Forecast")
show(arima_plt)


final_m_df <- mergeResults(data_df, m0, 'arima')



```









