---
title: "scratch"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```




```{r libraries, include=FALSE}


library(lubridate)
library(archive)
library(readr)
library(tidyr)
library(dplyr)
library(stringr)  

library(kableExtra)
library(ggpubr)
library(ggplot2)
library(ggcorrplot) 
library(patchwork)

library(prophet)
library(forecast)
library(tidyverse)
library(fable)
#library(fabletools)
library(tsibble)
library(tsibbledata)
library(feasts)
library(tseries)
library(modeltime)
library(yardstick)


```



```{r}
lag.length = 12


```


	
```{r}


mergeResults <- function(data_df, m0, modelName){
	
	multi_metric <- metric_set(rmse, rsq, msd, mae, mpe, mape, smape, mase)
	m1 <- data_df %>% multi_metric(truth=actual, estimate=predict)
	
	m <- merge(x = m0, y = m1, by = ".metric", all = TRUE)
	m
	
	# write final results
	m0 <- m0 %>% dplyr::rename(metric = .metric,
					 model = .model,
			         value = fable)
	m0$type <- 'fable'
	final_m_df <- rbind(final_m_df,m0 %>% dplyr::select(model,metric,type,value))
	
	
	m1 <- m1 %>% dplyr::rename(metric = .metric,
			         value = .estimate)
	m1$model <- modelName
	m1$type <- 'yardstick'
	final_m_df <- rbind(final_m_df,m1 %>% dplyr::select(model,metric,type,value))
	
	return(final_m_df)
}


```

	
	
	
```{r}

	destfile <- tempfile()
	download.file("https://datahub.io/core/s-and-p-500/r/data.csv",destfile)
	df <-  readr::read_csv(destfile)
	df$ds <- df$Date
	df$ds <- tsibble::yearmonth(df$ds)
	df$y <- df$SP500
	df <- df %>% dplyr::filter(ds > as.Date("1990-01-01"))
	#df$y.og <- df$y
	#df <- mutate(df, y = difference(y, order_by = ds, lag = 2, default = 0))
	#df <- mutate(df, y = difference(box_cox(y, 12), order_by = ds, lag = 2, default = 0))
	#df <- mutate(df, y = difference(box_cox(y, 2), order_by = ds, lag = 2, default = 0))
	#difference(box_cox(GDP, lambda_t), 1)

	#df <- df |> tidyr::drop_na(c(ds,y)) |> dplyr::distinct(ds,y)
	#df <- df |> dplyr::filter(!is.na(ds))

	tb <- df |> tsibble::as_tsibble(index = ds)
	tb <- tsibble::fill_gaps(tb, .full = TRUE, y = dplyr::last(y))
	
	#tb <- tb %>% dplyr::filter(ds > as.Date("2000-01-01"))
	#tb <- mutate(tb, y = difference(y, order_by = ds, lag = 3, default = 0))
	
	tb %>% autoplot(y)



```
	


	
	
```{r}

# df$
# 	
# df <- mutate(df, y.inv = diffinv(y, order_by = ds, lag = 2, default = 0))
# diffinv
# 
# 
# diffinv(df$y.inv, xi = df$y)
# diffinv(df$y, xi = as.vector(df$y))
# 
# 
# s <- 1:10
# d <- diff(s)
# d
# diffinv(d, xi = 1)

```

	
	
	


```{r}

test_tb <- tb 

#test_tb <- mutate(test_tb, y = difference(y, order_by = ds, lag = 2, default = 0))
#df <- mutate(df, y = difference(box_cox(y, 12), order_by = ds, lag = 2, default = 0))
#df <- mutate(df, y = difference(box_cox(y, 2), order_by = ds, lag = 2, default = 0))



lambda <- test_tb %>%
  features(y, features = guerrero) %>%
  pull(lambda_guerrero)

test_tb$y <- difference(box_cox(test_tb$y, lambda)) 
test_tb <- test_tb %>% dplyr::filter(!is.na(y))

#df <- df |> tidyr::drop_na(c(ds,y)) |> dplyr::distinct(ds,y)
#df <- df |> dplyr::filter(!is.na(ds))


# Ljung-Box test for independence (a non-stationary signal will have a low p-value)
print('=====')
bt_test <- Box.test(test_tb$y, lag=lag.length, type="Ljung-Box")
bt_test
print(paste0('- Ljung-Box test (stationary): ', bt_test$p.value > 0.05, ' at a p-value of ', round(bt_test$p.value,4)) )

# Augmented Dickey–Fuller (ADF) t-statistic test for unit root (a series with a trend line will have a unit root and result in a large p-value)
#H0 - The time series is non-stationary.
#HA - The time series is stationary.
print('')
print('=====')
adf_test <- adf.test(x=test_tb$y)
adf_test
#acf(a_tb$y,lag.max = length(a_tb$y),xlab = "lag #", ylab = 'ACF',main=' ')
print(paste0('- Dickey–Fuller (ADF) (stationary): ', adf_test$p.value < 0.05, ' at a p-value of ', round(adf_test$p.value,4)) )

# Kwiatkowski-Phillips-Schmidt-Shin (KPSS) for level or trend stationarity (a low p-value will indicate a signal that is not trend stationary, has a unit root)
print('')
print('=====')
kpss_test <- kpss.test(test_tb$y, null="Trend")
kpss_test
print(paste0('- Kwiatkowski-Phillips-Schmidt-Shin (KPSS) (trend stationary): ', kpss_test$p.value < 0.05, ' at a p-value of ', round(kpss_test$p.value,4)) )

test_tb %>% autoplot(y)


```



```{r}
# data(aus_production)
# 
# lambda <- aus_production %>%
#   features(Gas, features = guerrero) %>%
#   pull(lambda_guerrero)
# aus_production %>%
#   autoplot(box_cox(Gas, lambda)) +
#   labs(y = "",
#        title = latex2exp::TeX(paste0(
#          "Transformed gas production with $\\lambda$ = ",
#          round(lambda,2))))

```



```{r}

lambda <- test_tb %>%
  features(y, features = guerrero) %>%
  pull(lambda_guerrero)

test_tb %>%
  autoplot(box_cox(y, lambda)) +
  labs(y = "",
       title = latex2exp::TeX(paste0(
         "Transformed gas production with $\\lambda$ = ",
         round(lambda,2))))

```



```{r}
# setup results dataframe
final_m_df <- dplyr::data_frame(model=character(), 
								metric=character(), 
								type=character(),
								value=numeric())
```



```{r}

# setup train and validate tsibbles
data_n <- nrow(tb)
train_n <- floor(data_n * 0.7)
valid_n <- data_n - train_n

train_data <- tb |> slice(1:train_n)
valid_data <- tb |> slice(train_n+1:data_n)
new_data <- valid_data %>% select(ds,y) %>% as_tsibble(index = ds)

# view trainging data
ggplot(train_data, aes(x=ds)) +
			geom_line(aes(y=train_data$y), color="darkgray") 

```




```{r}
# calculate lambda
lambda <- test_tb %>%
  features(y, features = guerrero) %>%
  pull(lambda_guerrero)


# train model
fit <- train_data %>%
  #model(arima = ARIMA(box_cox(y, lambda) ~  trend(knots = yearquarter("2010 Q1")) + season() ))
  #model(arima = ARIMA(box_cox(y, lambda) ~  trend(knots = year("2010")) + season() ))
	#model(arima = ARIMA(box_cox(y, lambda) ~  trend() + season() ))
	model(ets = ETS(box_cox(y, lambda) ~  trend('M') + season('M') ))

	tryCatch( {gg_arma(fit %>% select(arima))},
			  error=function(e) { message(e)})

fit %>% report()

#components(fit) %>% autoplot()


	tryCatch( {fit %>% gg_tsresiduals()},
		  error=function(e) { message(e)})

	
m0 <- fabletools::accuracy(fit)
m0 <- m0 %>% pivot_longer(!c('.model','.type') ,names_to = ".metric", values_to = "fable")
m0$.metric <- tolower(m0$.metric)

# test model
fc <- fit %>% fabletools::forecast(new_data = new_data)
fc %>% autoplot(train_data)

data_df <- data.frame(
	predict =fc$.mean,
	actual = valid_data$y,
	month = valid_data$ds
)
arima_plt <- ggplot(data_df, aes(x=month)) +
				geom_line(aes(y=actual), color="darkgray") +
				geom_line(aes(y=predict), color="steelblue", linetype="twodash") +
				ggtitle("Arima Forecast")
show(arima_plt)

# arima_plt1 <- ggplot(data_df, aes(x=month)) +
# 				geom_line(aes(y=actual.og), color="darkgray") +
# 				geom_line(aes(y=predict.og), color="steelblue", linetype="twodash") +
# 				ggtitle("Arima Forecast (OG)")
# show(arima_plt1)

final_m_df <- mergeResults(data_df, m0, 'arima')



```



```{r}

final_m_df$value_round <- round(final_m_df$value,3)

```



```{r}



final_m_df %>% dplyr::filter(metric %in% c('mape','rsq','acf1','mase','rmse')) %>%
ggplot(aes(x=type, y=value, fill=metric)) + 
	geom_bar(stat = 'identity', position=position_dodge()) +
	facet_wrap(vars(metric),scales = "free") +
	ggtitle("Model Performance")

```






```{r}


yard_plt <- final_m_df %>% 
	dplyr::filter(metric %in% c('mape','rsq','acf1','mase','rmse')) %>%
	ggplot(aes(x=type, y=metric, fill=value_round, label=value_round)) + 
	geom_tile() + theme_bw() + 
	geom_text(aes(label=value_round, size=.6), color="black", size=3) +
	scale_fill_gradient(low = "lightgray", high = "red") + 
	theme_light() +
	ggtitle("Model Performance (Yardstick)")





yard_plt + plot_layout(ncol = 1) & theme(legend.position='right')

```












```{r}

set.seed(507)
## annual data
dat_1 <- rnorm(30) 
dat_yr <- ts(dat_1,start = 1991, end = 2020, frequency = 1)



## monthly data
dat_2 <- rnorm(30*12) 
dat_mo <- ts(dat_2,start = c(1991, 1), end = c(2020, 12), frequency = 12)




```






